FROM golang:1.21-alpine AS builder

WORKDIR /app
RUN apk add --no-cache git gcc musl-dev

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix nocgo -o ms_cart cmd/main.go


# ####################################################################
# ETAPA 2: FINAL - Crea la imagen ligera de producción
# ####################################################################
# Usamos una base muy pequeña (scratch) o alpine/slim si necesitas certificados SSL
FROM alpine:latest
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /app/ms_cart /app/
COPY .env /app/.env
EXPOSE 8080
CMD ["/app/ms_cart"]