apiVersion: v1
kind: Service
metadata:
  name: ms-auth-service
  labels:
    app: ms-auth
    tier: backend
spec:
  type: ClusterIP 
  selector:
    app: ms-auth
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001