apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-db-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath: 
    path: "/mnt/data/auth-db"
  persistentVolumeReclaimPolicy: Retain